### ISSUE TITLE
Is possible get list of pages?

### ISSUE THREAD

**Issue by descovi** [thoughtbot/high_voltage#123]
Is there a way to get a dynamic list of pages?

**Comment by bentoncreation** [comment]
@harlow Would you still be open to a PR for this functionality, provided it was good quality and the interface you want?

**Comment by phantomwhale** [comment]
Would love to see a PR for this - we are generating sitemaps too. Thanks @kim3er for the snippet to do this for us, for now. And advance thanks to @bentoncreation
