### ISSUE TITLE
Restrict High Voltage to a specific namespace

### ISSUE THREAD

**Issue by yazinsai** [thoughtbot/high_voltage#150]
I'm building a website with an API and I'm using High Voltage to display the static pages on the website.

Here is my `routes.rb` file:

``` ruby
MyApp::Application.routes.draw do

  namespace :api, path: '/', defaults: {format: 'json'}, \
    constraints: { subdomain: 'api' } do
    namespace :v1 do
      resources :cards, 
                :charges, 
                :customers
    end
  end

  namespace :website, path: '/', constraints: { subdomain: 'manage' } do
    resources :users, only: [:create, :update]
    resources :api_keys
  end

end
```

And here's what my `config/initializers/high_voltage.rb` file looks like:

``` ruby
HighVoltage.configure do |config|
  config.home_page = 'home'
  config.route_drawer = HighVoltage::RouteDrawers::Root
end
```

Now when I access `http://manage.myapp.com/about` it works fine. **The problem is** that when I access `http://api.myapp.com/about` it _also_ works. Is there a way to restrict High Voltage to run only in the `website` namespace?

**Comment by voordev** [comment]
Had the same issue, now is this still the best way to handle things or can it be solved more elegant in the latest version of high voltage?
