### ISSUE TITLE
Error browsing to page with HighVoltage used in an isolated engine

### ISSUE THREAD

**Issue by adamburmister** [thoughtbot/high_voltage#160]
Hey all, 

This is quite possibly a misconfiguration on my part, but would love to raise it in case it's not (or if you can provide some guidance).

I'm attempting to build an isolated engine which uses HighVoltage.
I've required high_voltage in the gemspec, within lib/my_engine.rb, and have a config/initializers/high_voltage.rb setup  as follows...

``` ruby
require 'high_voltage'

HighVoltage.configure do |config|
  config.parent_engine = MyEngine::Engine
  config.route_drawer = HighVoltage::RouteDrawers::Root
  config.home_page = 'home'
  config.layout = 'static_page'
end
```

I believe I've followed all instructions provided on the docs to configure the site, but am still receiving issues when browsing pages, where I get a "`uninitialized constant MyEngine::HighVoltage`" error.

Any suggestions as to a cause or possible fix?

Many thanks for the good work,
-A

**Comment by aaronmcadam** [comment]
Seems this issue still applies. Any pointers on how to fix this would be great!

**Comment by dgalarza** [comment]
@aaronmcadam have you tried disabling the routes that are generated by HighVoltage and instead manually setting it up within your engine?

**Comment by aaronmcadam** [comment]
@dgalarza Sorry about the delay. I've disabled the routes, yes.

**Comment by Svashta** [comment]
+1 here
Same need, same problem.
Getting No such page: home with override option.

**Comment by dangerdogz** [comment]
If this can helps someone :

I added the module successfully to Spree Commerce

**Routes**

```ruby
  Spree::Core::Engine.add_routes do
    get "/pages/:id" => 'pages#show', as: :page, format: false
  end
```

**config/high_voltage.rb**

```ruby
HighVoltage.configure do |config|
  config.routes = false
end
```

Then, I added a custom controller to Spree to handle the Pages

```ruby
module Spree
  class PagesController < Spree::StoreController
    include HighVoltage::StaticPage

    layout "spree/layouts/spree_application.html.erb"

  end
end
```

**Comment by aaronmcadam** [comment]
I've followed everything here and it works in development, but when I deploy, I get `/ruby/2.2.0/gems/high_voltage-2.4.0/app/controllers/high_voltage/pages_controller.rb:1:in `<top (required)>': uninitialized constant ApplicationController (NameError)`. I've been adding a top-level `app` directory with an empty `ApplicationController` for this to work and recently removed it to see if this was still a problem and it is.

**Comment by hansondr** [comment]
I've had success in development using the method @dangerdogz outlined above but ran into problems when I turned on eager loading.  I'm still working on a solution for the following error:

`.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/high_voltage-2.4.0/app/controllers/high_voltage/pages_controller.rb:1:in '<top (required)>': uninitialized constant ApplicationController (NameError)`

**Comment by StandardNerd** [comment]
@dangerdogz I followed exactly your workaround to add High Voltage in Spree/Solidus and it's working for url with the format pages/id but for the root url/homepage when no key/parameter is given I get the error message ActionController::UrlGenerationError in Spree::Home#index No route matches {:action=>"show", :controller=>"spree/pages"} missing required keys: [:id] 
How did you solve this issue?

**Comment by dgalarza** [comment]
Going to close this as there hasn't been much activity around it some time.
