### ISSUE TITLE
ActionController::RoutingError Help

### ISSUE THREAD

**Issue by ivycheung** [thoughtbot/high_voltage#164]
Hello,

I am having the Routing error issue with my production where I try to get to /about page, it cannot be found.

I think it may be due to I have my app loaded with a sub-folder structure.

```
config.relative_url_root = '/ljtimemachine'
```

I have a page at app/views/pages/about.html.erb and used 

```
HighVoltage.configure do |config|
  config.route_drawer = HighVoltage::RouteDrawers::Root
end
```

I tried accessing the page via ljtimemachine/pages/about and ljtimemachine/about and neither works.

(It works with development/localhost since it doesn't have the relative root url configured.)

Any suggestions? Thanks.

**Comment by brunoOSI** [comment]
Having that exact same issue. Seems like `config.relative_url_root` is not being used at all by high voltage.
