### ISSUE TITLE
prevent devise authentication

### ISSUE THREAD

**Issue by dtrac3** [thoughtbot/high_voltage#17]
I have the the gem configured at /pages/ and also have a controller PagesController. When I try to go to /pages/about it picks up my before_filter authenticate_user! I have added to my ApplicationController. How can i prevent authentication for my static pages?

**Comment by Arslan-Ali-Butt** [comment]
Is it still applicable with Rails `5.1.2`?

I'm doing the exact same thing, but it's not working.

I have tried modifying the routes to the following as well:

    match '/:id' => 'high_voltage/pages#show', controller: 'pages', as: :static, via: :get

What am I missing here?

**Comment by lpender** [comment]
In 2023:

```
# app/controllers/high_voltage/pages_controller.rb
class HighVoltage::PagesController < ApplicationController
  include HighVoltage::StaticPage

  skip_before_action :authenticate_user!
end
```
