### ISSUE TITLE
Question (not an issue): Why would I use high_voltage and not just create a static_pages controller?

### ISSUE THREAD

**Issue by HatStephens** [thoughtbot/high_voltage#190]
I'm sorry for asking this here, but SO doesn't like 'opinionated' questions.

I've just come across this gem and want to know what benefits there is to using this gem over creating a static_pages_controller? Maybe I've missed something in the README?

I understand how this works (I think) but would like to the benefits. I'm a newbie looking for 'best practices' and am keen to know the purpose of this route for managing static pages.

Thank you

**Comment by harlow** [comment]
Hi @HatStephens thanks for the note. 

In many cases a `static_pages_controller` will get the job done. However, there are a few cases where I think High Voltage shines:

1. When routes file starts getting messy with lots with static routes 
2. Nested pages i.e. `company/about/harlow_ward`

**Comment by HatStephens** [comment]
1. Understood. I do like not having to declare anything in the routes for each static page, although wonder whether that makes it harder for another developer to see what's going on?
2. I'm struggling with this one. Would the harlow_ward page be moved into the /pages directory then?

Thank you for taking the time on this.

**Comment by harlow** [comment]
> I'm struggling with this one. Would the harlow_ward page be moved into the /pages directory then?

Yes exactly. The path would look like this:

`app/views/pages/company/about/harlow_ward.html.erb`

And it would automatically be picked up by the route:

http://localhost:3000/company/about/harlow_ward

**Comment by HatStephens** [comment]
OK, I think I get it. Because, using a static_pages_controller you wouldn't be able to do that without adding a long line to the routes.rb file?
````match '/company/about/harlow_ward' => 'static_pages#harlow_ward', :via => :get````

**Comment by harlow** [comment]
> without adding a long line to the routes.rb file?
:+1:

**Comment by HatStephens** [comment]
Thank you @harlow appreciate your help with this. I'll see how I get on using it!
