### ISSUE TITLE
Image files cause WrongEncodingError

### ISSUE THREAD

**Issue by AMPearlman** [thoughtbot/high_voltage#191]
I have a folder that contains static content, both html and images. When the html references an image, I get a WrongEncodingError. This stack post mentions the problem in detail, including a "fix" but it seems like this should work out of the box. 

http://stackoverflow.com/questions/14860295/how-can-i-configure-high-voltage-gem-to-serve-up-static-images

**Comment by harlow** [comment]
@AMPearlman is there a reason you're not putting images into the `app/assets/images` directory? Thats the standard location for any static assets such as JS, CSS, and Images.

**Comment by AMPearlman** [comment]
Yes, here's my use case: I host several websites. I built a rails app that allows users to update their sites and publish html files. I use webalizer to generate stats for each site. Those stat files are static html and pngs. I'm using High Voltage to display those stat files within the rails app (which requires the tweak mentioned in the stackoverflow entry to work).

**Comment by mjankowski** [comment]
Serving images is out of scope for high voltage.

You could subclass the controller and do something custom if you need it to be routed that way ... but a better solution seems to be use another controller/route (if you can't use asset pipeline) to handle the image assets.
