### ISSUE TITLE
Problems using RouteDrawers::Root when app runs from subdirectory

### ISSUE THREAD

**Issue by nickjer** [thoughtbot/high_voltage#196]
I currently have an app that runs in a subdirectory, i.e.

```
http://www.domain.com/myapp/
```

I would like the static pages to appear as...

```
http://www.domain.com/myapp/home
http://www.domain.com/myapp/about
```

Unfortunately when using `HighVoltage::RouteDrawers::Root` it uses `request.path` on https://github.com/thoughtbot/high_voltage/blob/9114c11daab42487e3abf728c19b9f2810795a4e/lib/high_voltage/constraints/root_route.rb#L6

In my scenario this looks like... `request.path = /myapp/home`

So the `file_pattern` that it uses to search for the file is...

```
.../app/views/pages//myapp/home.html*
```

when it should be...

```
.../app/views/pages/home.html*
```

I tried googling around for a request method that stripped off the relative URL root from the request's path, but failed. Closest I could find was using `ENV['RAILS_RELATIVE_URL_ROOT']` to strip it from the `request.path`.

Any help on this would be greatly appreciated. Thanks!

**Comment by dgalarza** [comment]
Hi @nickjer. Would this issue simply be resolved by moving your views into `app/views/pages/myapp`?

**Comment by nickjer** [comment]
It probably would fix the problem, but there are quite a few apps and the apps are sometimes located under different sub-uri's depending on the environment they are running under. I don't want to keep changing the view's file structure depending on the sub-uri they are hosted under.

In the meantime I just applied my own patch to it that works for my case...

```
# config/initializers/high_voltage.rb

class HighVoltage::Constraints::RootRoute
  # Fixes: PassengerBaseURI not stripped from page_id
  def self.file_pattern(page_id)
    page_id = page_id.sub(/^#{ENV['RAILS_RELATIVE_URL_ROOT']}\//,"")
    "#{content_path}#{page_id}.html*"
  end
end

HighVoltage.configure do |config|
  config.route_drawer = HighVoltage::RouteDrawers::Root
end
```

Thanks for the response. Feel free to close this issue if you want.
