### ISSUE TITLE
Explain how this is different from normal ERB views

### ISSUE THREAD

**Issue by afeld** [thoughtbot/high_voltage#200]
Not trying to be a :trollface:, but after looking through the README a couple of times, I don't think I understand what this gem does that's different from normal Rails controllers+views? Might be helpful to include a short paragraph at the top explaining what it provides. Thanks!

/cc 

* https://github.com/afeld/html_pipeline_rails
* https://twitter.com/djcp/status/613373960433086464

**Comment by nickjer** [comment]
In my opinion the dynamic routing makes this shine. I currently use this with a simple markdown renderer `Redcarpet`. I just pull down a GitHub wiki and I am able to view the entire wiki using my personal layout with this gem. All the routes for the dozens of wiki pages just work.

**Comment by dgalarza** [comment]
HighVoltage allows you to crete static views without having to build a controller for each page your looking to have.

The current README goes into details on how to use HighVoltage which provides much context into it's benefits in comparison to normal `controllers + views`. If you feel that some more documentation could be provided to make it clearer, feel free to open a PR to expand on this.
