### ISSUE TITLE
Undefined method `page_ids'

### ISSUE THREAD

**Issue by benrmatthews** [thoughtbot/high_voltage#202]
I added both high voltage and sitemap generator gems to my gemfile. I added the given code to add all generated pages to the sitemap, but when I refreshed the sitemap I got the following error:

    Undefined method `page_ids' for HighVoltage:Module .

**Comment by vemv-kantox** [comment]
They need to bump project's version. For now:

`gem 'high_voltage', github: 'thoughtbot/high_voltage', ref: '1eba606b5cbf23ffe87f84d21460d5f33e26c281'`

**Comment by dgalarza** [comment]
This is now available in version `2.4.0`
