### ISSUE TITLE
Block access to static pages

### ISSUE THREAD

**Issue by MarcoDias7** [thoughtbot/high_voltage#203]
Hi,

I've been reading the tutorial, but couldn't made it work.

I have some statics pages, that I want to be locked unless the user is logged. I have a Session helper with this :

  def logged_in?
    !current_user.nil?
  end

And I created my PagesController :

class PagesController < HighVoltage::PagesController
  before_filter :authenticate

  def authenticate
    unless logged_in?
      store_location
      flash[:danger] = "Please login first"
      redirect_to login_path
    end
  end

I assume I have to write something in my routes.rb file. I've already used a static page as homepage :
root :to => 'high_voltage/pages#show', :id => 'home'

What else have I to write in the routes.rb file to activate my PagesController, and what do I have to write to block access to my file.html.erb which is in views/pages ?

Thanks

**Comment by MarcoDias7** [comment]
I succeeded by doing this :

Writing this in initializers/high_voltage.rb :

HighVoltage.configure do |config|
  config.routes = false
end

My PagesController :

class PagesController < ApplicationController
  include HighVoltage::StaticPage
  before_action :authenticate

  def authenticate
    unless logged_in?
      store_location
      flash[:danger] = "Please login first"
      redirect_to login_path
    end
  end
end

And my routes.rb :

root :to => 'high_voltage/pages#show', :id => 'home'
  resources :tests
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :pages

  get 'pages/getdate'  => 'api#getdate'

The thing is, I have a problem now. I can still go to my home without being logged in by doing link_to root_url, one of my static pages uses the service "get 'pages/getdate'  => 'api#getdate'" and now it's not loading when we go to that page. 
The other problem is that there are some static pages that don't require this authentication, so, how to tell Rails that I only want some of the pages to be locked ?

**Comment by dgalarza** [comment]
> The thing is, I have a problem now. I can still go to my home without being logged in by doing link_to root_url, one of my static pages uses the service "get 'pages/getdate' => 'api#getdate'" and now it's not loading when we go to that page. 

I'm not sure I follow the issue here. Can you provide any more details on this issue?

> The other problem is that there are some static pages that don't require this authentication, so, how to tell Rails that I only want some of the pages to be locked ?

Perhaps you can have a `before_action` that is customized for your static pages which checks to see if the page id is available publicly or not.
