### ISSUE TITLE
Folder at / app root instead /app/views

### ISSUE THREAD

**Issue by prem-prakash** [thoughtbot/high_voltage#204]
I am trying to use high_voltage to serve my app yard generated docs.

But:

 - it seems the only folder we can use is inside /app/views/ , I am trying to use it to access /doc folder
Is it possible to do?

 - it seems that we can only return text/html mime type, and since doc has its own css and js on the same folder, these files are not loaded correctly. Is it possible to change mime type?

Do you have some suggestion about?

PS: I cannot serve it on /public because I must have an authentication on it.

**Comment by dgalarza** [comment]
Since `HighVoltage` requires the rails stack I do not believe that you would be able to access pages within `/doc` instead. 

> it seems that we can only return text/html mime type, and since doc has its own css and js on the same folder, these files are not loaded correctly. Is it possible to change mime type?

HighVoltage is designed for static pages and serving file types like CSS and javascript is out of scope for HighVoltage.
