### ISSUE TITLE
What if static page has a form?

### ISSUE THREAD

**Issue by simkessy** [thoughtbot/high_voltage#209]
Hi, This isn't an issue more of a question on how it would be best to proceed. I'm using static pages for things like about / terms of service / faq and now I'm adding a page called Partners. 

This page, needs to have a form, a mailer, etc. Does it make sense to create a `partners_controller` for this or is there a way to do this with High_Voltage? I looked at the READMe and it described how to override the controller but I see now that if I do this, the url contains `/pages/` which I'd rather not have. I like the default where it just follows the folder tree.

**Comment by dgalarza** [comment]
Hi @simkessy,

It sounds like your Partners page wouldn't belong as a high voltage page. Rather, you'd want to have an actual controller and view for handling it.
