### ISSUE TITLE
Access a list of Page URLs, not Page ids

### ISSUE THREAD

**Issue by robbiehudson** [thoughtbot/high_voltage#210]
Hey,

I'm trying to build a sitemap using the [sitemap generator gem](https://github.com/kjvarga/sitemap_generator) and following what's suggested in the README. However, this returns a list of IDs, not URLs for our pages. I'd love to be able to get a list of the actual URLs so I can build a proper sitemap.

Thanks,

Rob

**Comment by vemv** [comment]
Use page_url/page_path:
```ruby
HighVoltage.page_ids.each do |page|
 add_to_sitemap page_url(page)
end
```

**Comment by dgalarza** [comment]
Having the URLs is a bit out of scope of the `page_ids` method. The results should give you enough to build out a site map as @vemv mentioned.
