### ISSUE TITLE
Bare .haml extension not recognised by HighVoltage.page_ids

### ISSUE THREAD

**Issue by vemv** [thoughtbot/high_voltage#211]
The `haml-rails` gem (as opposed to `haml`) allows one to name its views `foo.haml` instead of the more cumbersome `foo.html.haml`.

However HighVoltage.page_ids does not list shortcutted pages, even if they are rendered when one visits `/pages/foo`.

In other words: high_voltage plays fine with haml-rails except for shortcutted names which aren't included in `HighVoltage.page_ids`.

Could you please address this?

Thanks!

Victor

**Comment by Elishanto** [comment]
Remove `&& html?` from [page.rb](https://github.com/thoughtbot/high_voltage/blob/master/lib/high_voltage/page.rb#L15).
It disables check for matching filename with this pattern `/\.(html)(\.[a-z]+)?$/`
