### ISSUE TITLE
link with anchor

### ISSUE THREAD

**Issue by michalwkrak** [thoughtbot/high_voltage#212]
I have a problem with HighVoltage when I try to link to anchor on the static page. In the URL I am receiving '%23' instead of '#'.

Example:

       <%= link_to 'xxx', page_path('xxx#yyy') %>

gives in the URL:

       http://localhost:3000/pages/xxx%23yyy

Can you give me a hint how it can be solved?

**Comment by dgalarza** [comment]
Hello @michalwkrak this is out of the scope of HighVoltage and is related to the usage of `link_to`. Please see the `link_to` documentation and how to use anchors with it. http://api.rubyonrails.org/classes/ActionView/Helpers/UrlHelper.html#method-i-link_to
