### ISSUE TITLE
How to setup a 404 page?

### ISSUE THREAD

**Issue by frarees** [thoughtbot/high_voltage#23]
I've been looking on how to set this up to render a page when a template is not found. Can anyone help me with this? Thank you all.

**Comment by yevgenko** [comment]
It is depend on particular use case, but in case someone looking to simply handle invalid pages:

```ruby
class PagesController < ApplicationController
  include HighVoltage::StaticPage

  def invalid_page
    render('pages/404-error', :status => 404)
  end
end
```

Please see "Override" scection for more details about PagesController:
https://github.com/thoughtbot/high_voltage#override

p.s.
`invalid_page` is the method from `HighVoltage::StaticPage` module, which, by default, raises `ActionController::RoutingError`  https://github.com/thoughtbot/high_voltage/blob/54217603f6745a1feecff6761bc600dc07631ba4/app/controllers/concerns/high_voltage/static_page.rb#L22-L24
