### ISSUE TITLE
PagesController: current_page as helper?

### ISSUE THREAD

**Issue by lowjoel** [thoughtbot/high_voltage#235]
54217603f6745a1feecff6761bc600dc07631ba4 removes the use of `hide_action` for `current_page`, now it is private. Can it be exposed as a helper instead? Views might need to use that information -- in my case, to generate the appropriate set of page CSS classes depending on the page being shown.

**Comment by dgalarza** [comment]
Exposing `current_page` as a helper sounds reasonable to me. Feel free to open a PR for this 😄

**Comment by Sathors** [comment]
Is there any news of this issue?

I am trying to find the name of the current page within a view, and I cannot get my head around it.

Thanks

**Comment by BreahnaDavid** [comment]
what about `params[:id]` -> ?

**Comment by dgalarza** [comment]
PR #245  has since been merged with 1f85fa6c5e4f8714d8d02cfa338d844fa87cbb20. So this will be available soon.
