### ISSUE TITLE
High_voltage and Pundit, only auth some pages?

### ISSUE THREAD

**Issue by rchady** [thoughtbot/high_voltage#236]
I want to use high_voltage for most pages, but then have only a couple that require a user to be logged in to view.  Tried following the README for it, but ran in to a mixture of issues, probably compounded by me trying various things.

What I want to have is:
- root route set to / instead of /pages
- /help and /contact require a user to be logged in
- /<all other static pages here> just displayed as usual

I am using Pundit and have it set to require authorization everywhere.  Is it possible to do this and still use high_voltage?

**Comment by dgalarza** [comment]
@rchady I am not familiar with `Pundit` however, you could potentially resolve this by overriding the pages controller as documented in https://github.com/thoughtbot/high_voltage#override to conditionally run authentication on some pages and not others.
