### ISSUE TITLE
Allow different extensions types in Views

### ISSUE THREAD

**Issue by BreahnaDavid** [thoughtbot/high_voltage#247]
Right now, with this configuration:
```
# config/initializers/high_voltage.rb
HighVoltage.configure do |config|
  config.route_drawer = HighVoltage::RouteDrawers::Root
end
```

We can't access:
`localhost:3000/pages/about`
if about view doesn't contain `.html` in its filename

so if we use `about.haml` `about.json` or any other extensions `about.xxx`
it will never work

but above enumerated extensions are views too

**Comment by BreahnaDavid** [comment]
https://github.com/BreahnaDavid/experience/pull/1

here is an example of code that doesn't work

**Comment by dgalarza** [comment]
This has been resolved as part of https://github.com/thoughtbot/high_voltage/pull/253
