### ISSUE TITLE
It seems do not support 5.1.0.beta1

### ISSUE THREAD

**Issue by sundevilyang** [thoughtbot/high_voltage#248]
As the title mentioned, when visit the static pages, it reports error "No route matches [GET]"

**Comment by HoracioChavez** [comment]
I just tried with `5.1.0.beta1` and it seems to work just fine. 
Maybe this could help you: https://github.com/thoughtbot/high_voltage#routing-overview

**Comment by jasnow** [comment]
Works for me too.

**Comment by dgalarza** [comment]
With Rails 5.1 release, we're actively testing against it and things look like they are working well. If you have any issues please feel free to re-open.
