### ISSUE TITLE
Send static pages through "mini" template while still utilizing main application layout?

### ISSUE THREAD

**Issue by professorNim** [thoughtbot/high_voltage#256]
Is there a way to use high_voltage to send the contents of each static page through one "mini" template? I want to use my base application layout, so I'm not sure changing the layout config option is the correct method. For example, rather than style each static page with markup that will be repeated across each static page, define one template that is rendered within the main application layout, and send the contents of each static page into that template?

**Comment by dgalarza** [comment]
It sounds like a custom layout would probably work best in your case here. Shared behavior between the layouts could potentially be encaspulated by extracting partials to be used in each layout.

You could also checkout Rails' support for nested layouts, though it's quite minimal. http://guides.rubyonrails.org/layouts_and_rendering.html#using-nested-layouts
