### ISSUE TITLE
page not found - double directory

### ISSUE THREAD

**Issue by jakebaird** [thoughtbot/high_voltage#260]
Hey guys, I'm fairly new to rails, I'm playing around with this gem and it's great. If I'm not at the root (say I'm at the about page) and I click the contact page, it'll double render the page URL so localhost:3000/pages/pages/contact

Any idea how to rectify this??

**Comment by dgalarza** [comment]
Sounds like this might be a relative vs absolute path problem. What do your links look like? Is it something like "pages/contact"?

**Comment by dgalarza** [comment]
Closing for now, feel free to reopen if you're still having this issue.
