### ISSUE TITLE
reconsidering use of ActionController::RoutingError

### ISSUE THREAD

**Issue by jjb** [thoughtbot/high_voltage#261]
If the PagesController can't find an appropriate template to use for a page id, it raise `ActionController::RoutingError`: https://github.com/thoughtbot/high_voltage/blob/master/app/controllers/concerns/high_voltage/static_page.rb

As far as I know, Rails itself only every raises `ActionController::RoutingError` in the router. It never does so in a controller.

I just spent a couple hours trying to debug my routes because bug was raising `ActionController::RoutingError` and I assumed it was a problem with my routes.

now...

a) i might be wrong that it's only ever raised in routes, pre-controller
b) maybe even if i'm right, it's arguably an appropriate exception to raise, because high_voltage serves this top-level routing role.

But I just wanted to raise (rimshot) the issue and see what other folks though. I would be in favor of high voltage having its own PageTemplateNotFound error, something like that.

**Comment by dgalarza** [comment]
Sorry to hear you had some trouble debugging the routing error @jjb. I believe it's common convention for raising a routing error when something is not found as it then maps to a 404 not found error on the Rails side of things. If we used a custom error in production, it would not properly map to a 404 if a user tried to go to a page which did not exist.

**Comment by jjb** [comment]
@dgalarza gotcha. how about this? 😄 

```ruby
class HighVoltage::PageTemplateNotFoundError < ActionController::RoutingError; end
```
