### ISSUE TITLE
Cannot add I18n for root

### ISSUE THREAD

**Issue by damienlethiec** [thoughtbot/high_voltage#263]
Hi there,

It seems that the I18n config for High Voltage is not enough to make it work for the root path. Everything works fine otherwise but when I go to `localhost:3000/en` to show my root path in English (my app is in French), High Voltage things `en` is the name of my page and tells me I don't have an `en.html.erb` file in my `views/pages` folder.

Any thoughts about this? For the moment I created a pages controller to handle my home page with I18n but I would love to be able to manage it with High Voltage.

Thanks a lot,
Damien

**Comment by dgalarza** [comment]
Hi @damienlethiec.

In order to utilize I18n configuration you'll likely need to disable the autogenerated routes provided by HighVoltage and instead implement your own.

See https://github.com/thoughtbot/high_voltage#localization

**Comment by damienlethiec** [comment]
Yes, that is what I thought! Thanks
