### ISSUE TITLE
Just Adding to Gemfile and Bundling Results in Error in Starting Rails Environment

### ISSUE THREAD

**Issue by mark100net** [thoughtbot/high_voltage#268]
Rails version: 5.1.4
Ruby version: 2.5.1

Adding to end of Gemfile like this:

gem 'high_voltage', '~> 3.0.0'

Error:

    undefined method `routes' for nil:NilClass (NoMethodError)

That's the only output.

**Comment by BerkhanBerkdemir** [comment]
Could you explain a bit more because it is not clear. :disappointed:

**Comment by mjankowski** [comment]
I'm going to close this on the assumption that it's not a problem any longer, please re-open if it is.
