### ISSUE TITLE
"Danger" video not available

### ISSUE THREAD

**Issue by janklimo** [thoughtbot/high_voltage#274]
I'm curious 😅 
https://www.youtube.com/watch?v=HD5tnb2RBYg

**Comment by kfpo** [comment]
This is quite crucial... Maybe change it to https://www.youtube.com/watch?v=wbIXlf22qnM&t=82s ? :smiley:

**Comment by besi** [comment]
> Video unavailable
> This video contains content from [Merlin] Beggars, who has blocked it on copyright grounds.

**Comment by bjgaynor** [comment]
I'm glad some folks are talking about the real issues here :)
