### ISSUE TITLE
Unable to catch missing pages

### ISSUE THREAD

**Issue by EllieRagone** [thoughtbot/high_voltage#275]
I previously used these lines in my `routes.rb` file to catch all missing pages and display a nice-looking 404 pages:

```
   unless Rails.application.config.consider_all_requests_local
      match '*path', to: 'errors#error_404', via: :all
   end
```

However, it seems that HighVoltage is waiting for the routes file to fail through completely before picking things up, so this route is matching my static pages that I want high voltage to handle.  Any thoughts on tweaking my setup here to account for high voltage?

Thanks in advance!

**Comment by bensheldon** [comment]
@pcragone I ran into that problem too. You can defer defining your catch-all route like this:

```rb
# routes.rb

Rails.application.routes.draw do
  # ...
end

Rails.application.config.after_initialize do |application|
  unless Rails.application.config.consider_all_requests_local
    application.routes.append { match '*path', to: 'errors#error_404', via: :all }
  end
end
```

**Comment by iainbeeston** [comment]
High voltage provides an [invalid_page method](https://github.com/thoughtbot/high_voltage/blob/1b5012986ac7e243717b77ee7e06425f069534dd/app/controllers/concerns/high_voltage/static_page.rb#L25) for exactly this. If define your own high voltage controller, then define `invalid_page` in it, you can make it redirect or render a custom 404 or whatever you like.

**Comment by mjankowski** [comment]
Closing this on the assumption that the prior few comments were useful and resolved the issue.

**Comment by essn** [comment]
@bensheldon @EllieRagone I had an issue where the pages controller acting as a catch-all was throwing 5xx, particularly for stale stylesheets.

**Comment by essn** [comment]
@bensheldon @EllieRagone I had an issue where the pages controller acting as a catch-all route was throwing a 5xx, especially with stale stylesheets.

I managed to fix it using [invalid_page](https://github.com/thoughtbot/high_voltage/blob/1b5012986ac7e243717b77ee7e06425f069534dd/app/controllers/concerns/high_voltage/static_page.rb#L25) with the following snippet if anyone finds it helpful:

```ruby
def invalid_page
  render('404', status: :not_found, formats: [:HTML])
end
```
