### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by patrickdavey** [thoughtbot/high_voltage#279]
Hi there,

Just wondering if there is a plan to release a new version of this gem? There hasn't been a new release since May 2018 and there are now almost 100 commits against master merged in.

If not, and you expect people to just link against the `master` branch or similar, should we update the README to suggest that people do that?

Thanks for the great gem :)

**Comment by voordev** [comment]
Would love to know too
Please release a new version.
Was working on rolling my own bit this is perfect to implement

**Comment by voordev** [comment]
Anyone?
@croaky @mjankowski @timurvafin

**Comment by mjankowski** [comment]
Thanks for the ping -- the vast majority of those commits are developer environment commits which don't impact the behavior of the library itself ... but there is at least one bugfix in there. I'll submit a PR to put out a `2.4.1` release to at least include that one change.
