### ISSUE TITLE
[Help] Different Layouts At Root Level

### ISSUE THREAD

**Issue by richjdsmith** [thoughtbot/high_voltage#286]
Is it possible to assign some static pages one layout, and others a different one while still having them managed through High Voltage?

**Comment by richjdsmith** [comment]
Sorry, to clarify - I want to do this one while still managing the pages with High Voltage as well as keeping the pages at root level (via setting `route_drawer` to `HighVoltage::RouteDrawers::Root`)

**Comment by justalever** [comment]
+1 for this. Running into a wall where I need custom layouts for some pages but am forced to use a`/page/id` like url structure.

**Comment by chai2** [comment]
+1

**Comment by mrsousa** [comment]
I was using as described on the documentation:

> # config/initializers/high_voltage.rb
> 'HighVoltage.configure do |config|'
>  'config.route_drawer = HighVoltage::RouteDrawers::Root'
>  'config.routes = false'
> 'end'

>#routes.rb
> 'get "/pages/*id" => 'pages#show', as: :page, format: false'

But that end up breaking my active-storage routes (image links).

So, I had to add a constraint on my rout, and it worked for me:

`get "/*id" => 'pages#show', as: :page, format: false, :constraints => HighVoltage::Constraints::RootRoute.new`

**Comment by richjdsmith** [comment]
Thanks @mrsousa! That solved it!

**Comment by richjdsmith** [comment]
Closing this as @mrsousa's solution solved all issues.
