### ISSUE TITLE
Does High Voltage Work Under Rails 6?

### ISSUE THREAD

**Issue by fuzzygroup** [thoughtbot/high_voltage#289]
I just moved my codebase to Rails 6 and noticed that I always get 500 errors on my static pages:

Started GET "/pages/faq" for ::1 at 2019-09-25 07:29:51 -0400
Processing by HighVoltage::PagesController#show as HTML
  Parameters: {"id"=>"faq"}
  Rendering pages/faq.md within layouts/application
  Rendered pages/faq.md within layouts/application (Duration: 2.9ms | Allocations: 901)
Completed 500 Internal Server Error in 11ms (ActiveRecord: 0.0ms | Allocations: 1795)

Any insights?

**Comment by mjankowski** [comment]
I have a rails six WIP branch going, and just opened a PR to add it into the specs we run.

Are you able to get a more detailed backtrace on that request to expose where the error is coming from?

**Comment by fuzzygroup** [comment]
Unfortunately that is as detailed as the error message seems to be

**Comment by fuzzygroup** [comment]
I was using this with kramdown-rails and the issue seems to be the markdown conversion.  I'm closing this since the issue isn't high voltage.  I suspect the issue is the change in render template from 1 parameter to 2 parameters but that is as far as I was able to debug it.  Apologies.
