### ISSUE TITLE
Invalid constraint: HighVoltage::Constraints::RootRoute must respond to :call or :matches? (ArgumentError)

### ISSUE THREAD

**Issue by valentinbotog** [thoughtbot/high_voltage#301]
Hi,

I was upgrading me RoR app, from ruby 2.3.0 to ruby 2.4.6 and from rails 4.2.5.1 to rails 5.2.2 ,  and when I try to start rails server I get next error: 
"Invalid constraint: HighVoltage::Constraints::RootRoute must respond to :call or :matches? (ArgumentError)".
no changes to config/initializers/high_voltage.rb which have next lines:
HighVoltage.configure do |config|
  config.content_path = 'inverter_pages/'
  config.routes = false
end

also no changes in my routes.rb file
 root to: 'high_voltage_pages#show', id: 'home'
 get "/*id" => 'high_voltage_pages#show', as: :page, format: false, :constraints => HighVoltage::Constraints::RootRoute

Thanks in advance.

**Comment by mjankowski** [comment]
Can you confirm which of those steps (ruby upgrade or rails upgrade) caused the issue?

Separately, which version of high voltage do you have installed?

**Comment by valentinbotog** [comment]
I did both upgrades in the same time(changed my gemfile), after that I was running bundle update.
High Voltage version from Gemfile.lock -> high_voltage (3.1.2)

The issue was that no other routes were working after the line : get "/*id" => 'high_voltage_pages#show', as: :page, format: false, :constraints => HighVoltage::Constraints::RootRoute

My solution was to change the line to:
get "/*id" => 'high_voltage_pages#show', as: :page, format: false
and to move it at the end of routes.rb file

**Comment by mjankowski** [comment]
Thanks. Closing on assumption that there's nothing more to do here.

**Comment by valentinbotog** [comment]
Thanks for your fast intervention. Have a great day.

**Comment by antwonlee** [comment]
@valentinbotog solution worked for me as well, but I am wondering how that solution is different from having constraints.  I am not sure why I am getting:

"Invalid constraint: HighVoltage::Constraints::RootRoute must respond to :call or :matches? (ArgumentError)"

This doesn't happen in 3.0.0.
