### ISSUE TITLE
Routes not drawn on the latest Rails (main)

### ISSUE THREAD

**Issue by luizkowalski** [thoughtbot/high_voltage#327]
hey 👋🏻 

I'm using Rails edge and noticed that since last week, the routes for HighVoltage are not drawn anymore, `rails routes` doesn't show any, and `page_path` raises MethodMissingError

I managed to fix it by manually drawing it like this: 

```ruby
get(**HighVoltage.route_drawer.match_attributes)
```

**Comment by luizkowalski** [comment]
possibly related: https://github.com/rails/rails/pull/52353

**Comment by emilford** [comment]
Thanks for opening this issue @luizkowalski! The change you linked to looks like a likely culprit.

If you want to take a crack at solving it, PRs are appreciated. Otherwise, we'll keep it on the radar to look into soon.

**Comment by luizkowalski** [comment]
It appears the breaking changes were reversed and it is working as expected now without any tweaking: https://github.com/rails/rails/pull/52664
