### ISSUE TITLE
wrong url generation with scope declared

### ISSUE THREAD

**Issue by aboutlo** [thoughtbot/high_voltage#59]
define a route like that:

scope "/(:locale)"  do
   match "/*id" => 'high_voltage/pages#show', :as => :page,  :format => false
end

create a link with this helper:
page_path("about")

you get:
No route matches {:controller=>"high_voltage/pages", :action=>"show", :locale=>"about"}

rather using page_path(:id => "about") it works fine and you get "/locale/tour"

**Comment by notrab** [comment]
How are we getting on with this?

Also, should I be experiencing issues linking to nested pages?

E.g. 

```
link_to "Privacy Policy", page_path(id: 'legal/privacy-policy')
```

Doesn't understand the `/` only when using the `id:` setter.
